### PR TITLE
Allow non-expiring jobs, set this as the default.

### LINKED ISSUE #22: Support non-expiring jobs
Currently, jobs expire after 1 day of staying in the queue.  We should instead allow them to be set to never expire.

### PR DESCRIPTION
**Pull request by TimOrme**
Allows for jobs to never expire, and makes this the default.

Closes #22

### CODE REVIEW

**Comment by inactivist** [comment]
I'm fine with supporting non-expiring jobs, but I do have some concerns about making this the default behavior.  What's the use case/rationale for the new default behavior?

I'm of two minds on this.  I'm trying to figure out which behavior is least astonishing  ([POLA](https://lucumr.pocoo.org/2011/7/9/python-and-pola/)) for people using `narq`

**Comment by TimOrme** [comment]
Well, for me, the default expiring behavior resulted in loss of data, which I think is worse.  My expectation is that if I fire off a job I'm anticipating it to run, basically no matter what, unless I explicitly want to state that it's ok for this job to disappear after some time.

I understand that it can cause clutter in the event that you have buggy code, but I think thats preferable to having lost the data.

I do want to update the client however to be able to set a default for all `enqueue_job` calls, that can then be overridden per-call.  Thinking about this though, think I might change the indicator here to be a negative number instead, such that:

```
expires = None # Indicates to use the default from the connection
expires = -x # indicates to never expire.
```

Thoughts?

**Review by inactivist — COMMENTED** [review]
> Well, for me, the default expiring behavior resulted in loss of data, which I think is worse. My expectation is that if I fire off a job I'm anticipating it to run, basically no matter what, unless I explicitly want to state that it's ok for this job to disappear after some time.
> 
> I understand that it can cause clutter in the event that you have buggy code, but I think thats preferable to having lost the data.

Yeah that's a bad outcome for sure.  And, I agree that it makes sense to support non-expiring jobs.  Though I think my real concern is with the default behavior.  Is that what most users would expect?  I can't answer that, so I'll defer to you.

> 
> I do want to update the client however to be able to set a default for all `enqueue_job` calls, that can then be overridden per-call. Thinking about this though, think I might change the indicator here to be a negative number instead, such that:
> 
> ```
> expires = None # Indicates to use the default from the connection
> expires = -x # indicates to never expire.

That magic `-x` feels weird to me.  

Also, I think setting a per-connection default behavior may also lead to subtle bugs.  _Explicit is better than implicit_ ?

**Review by inactivist — APPROVED** [review]
LGTM

**Pull request merged**
